[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.31
    lvgl/lvgl@^8.3.9
    Links2004/arduinoVNC@^1.5
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_2_DRIVER=1
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=55000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D LV_CONF_SKIP=1
    -D LV_TICK_CUSTOM=1
    -D LV_COLOR_DEPTH=16
    ; --- Включаем кириллицу и шрифты для Русского Языка ---
    -D LV_TXT_ENC=LV_TXT_ENC_UTF8
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_DEFAULT=\&lv_font_montserrat_14
