name: PlatformIO Mega Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: какоии та чекаут
        uses: actions/checkout@v3

      - name: змеяпайтон установка
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: еспишку ставим
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Строить Шить
        run: pio run
